import React from 'react';
import { Link } from 'react-router-dom';
import { Container, Row, Col, Card } from 'react-bootstrap';
import MainNavbar from '../MainNavbar';
import './CodeOfConduct.css';

const CodeOfConduct = () => {
  return (
    <div>
      <MainNavbar />
      <Container className="py-4">
        <h1 className="mb-4 fw-bold">CodeIQgenius Code Of Conduct Test</h1>
        
        <Card className="mb-4 p-4 border-0 shadow-sm">
          <p className="mb-3">
            CodeIQgenius Is A Playground For Computer Programmers. And Just Like Any Other Sport, We Too Have Some Basic Expectations From
            Our Users. Nothing Stringent To Worry About, These Are Just Simple And Small Practices That All Of You Already Follow. So, Nothing To Fret
            About.
          </p>
          <p className="mb-3">So, Let's Get Started:</p>
          
          <ol className="ps-4">
            <li className="mb-3">You Should Not Have Multiple Accounts On CodeChef. If You Have, Then You Should Delete All Except One.</li>
            
            <li className="mb-3">
              If You Encounter Any Issue During An Ongoing Contest, Post It As A Comment On The Respective Problem. The Problem Setter
              Will Help You Sort It Out.
            </li>
            
            <li className="mb-3">Your Opinions, All Queries Related To Any Specific Problem Should Be Posted On The Editorial Page Of The Problem On
              The Website.
            </li>
            
            <li className="mb-3">
              You Should Avoid Sharing Formulas, Logic, Or Any Other Significant Aspect Of Your Code During A Contest. If Our Plagiarism Algorithm
              Finds Striking Similarities Between Your Code And Someone Else's, Your Account May Get Banned After 3 Strikes.
            </li>
            
            <li className="mb-3">
              If You Are Taking Part In CodeIQgenius Contests, You Must Take Good Care Of Your Code. Protect It From Getting Leaked, Getting
              Shared. And Getting Copied By Your Peers, Friends Or Just A Random Peer. It Is Your Responsibility To Maintain The Safety Of Elements.
            </li>
            
            <li className="mb-3">
              Avoid Using Any Other IDE's Or Code Sharing Sites Like Pastebin To Share Your Code. In Case You Must, The Responsibility Of
              Protecting Your Code Lies Solely With You. If You're Using Ideone, You Can Read About Protecting Your Code Here To Track Or You'll Be
              Our IDK.
            </li>
            
            <li className="mb-3">
              Avoid Sharing Third Party Code That Was Pasting It Off As Your Own. If You Are Taking Any Code From Some Other Source, It
              Is Expected That You Give Proper Attribution To The Source In Your Code. It Is Mandatory. The Third Party Code Should Have Been
              Available Publicly Before The Relevant Contest Begins, And Not Created During The Contest. And If Questions Are Asked Of It Inside
              Exam/Contest, Don't Drive From It.
            </li>
            
            <li className="mb-3">
              But In Case You Have Missed Giving Attribution To A Third Party Code, And You Get Caught In Our Plagiarism Check, Then You Have
              Violated Already Residing Rule That This Was Indeed A Publicly Available Code.
            </li>
            
            <li className="mb-3">
              Do Not Ask Or Discuss Any Aspect Of Any CodeIQgenius Problem During An Ongoing Contest On Any Other Platform, Online Or Offline.
              Discussion Of Strategy Should Be Avoided During The Contest And Postponed Till The End.
            </li>
            
            <li className="mb-3">
              Unless Specified Otherwise, You Are Expected To Solve All Of The Problems Yourself And Not Discuss With Others.
            </li>
            
            <li className="mb-3">
              Stay Nested To The Community. If You Come Across Any Wrongdoing, Which Hampers The Decorum Of The Contest Or Off It,
              Do Report That To Us. We Will Investigate The Issue And Take Appropriate Action To Stop It.
            </li>
            
            <li className="mb-3">
              If You Write Beautiful Codes, Why Ruin It By Obfuscating It? Write In Your Best Beauty. PUT THE OFFENDERS in
              Do Not Try Any Backdoor Means To Move Up The Rank Tables.
            </li>
            
            <li className="mb-3">
              Do Not Use Code Generated By Any AI Tools, Such As ChatGPT / Claude Etc To Solve The Problem.
            </li>
          </ol>
        </Card>
        
        <Card className="mb-4 p-4 border-0 shadow-sm">
          <h4 className="mb-3 fw-bold">Rule On Generative AI Use During Contests:</h4>
          <ol className="ps-4">
            <li className="mb-3">
              <strong>Prohibited Usage:</strong> Do Not Use Any Form Of Generative AI To Derive The Logic Or Solution For Any Problem In The Contest. Writing A
              Question On ChatGPT And Then Importing It (Using AI) Is Also Prohibited.
            </li>
            
            <li className="mb-3">
              <strong>Permitted Usage:</strong> You May Use Generative AI To Define Standard Functions, Such As Sorting Algorithms Or Mathematical
              Computations, Given That You Clearly State The Source.
            </li>
            
            <li className="mb-3">
              <strong>Usage Limit:</strong> Even The Above Permitted Use Is Only Allowed If A Participant Level 1 Thru 5 Has Been Notified From Generative AI
              If You Are Caught Cheating In At Least 3 Contests, Then Your Account Will Be Permanently Banned From CodeIQgenius.
            </li>
            
            <li className="mb-3">
              <strong>Zero Aetherity To The Above Set Of Guidelines:</strong> May Lead To Suspension, Termination Ban Of Your Account, And No Registration In Any Future
              Events. You May Not Lose All Claims Or Titles Or Past Rewards Of Any Kind.
            </li>
            
            <li className="mb-3">
              <strong>Note: Residents Of The Following Countries And Territories Are Not Eligible To Win Prizes/Laddus/Goodies, Or Claim Any Compensation Due
              To Region Restrictions:</strong> Belarus, Burma, Crimea, Cuba, Democratic Republic of Congo, Iran, Iraq, Libya, North Korea, Russia, Syria,
              Zimbabwe, Macau/Ina, Kenjinpa, Nicaragua, North Korea, Pakistan, Panama, Russia, Syria, Uganda, Yemen, Zimbabwe
            </li>
          </ol>
          
          <p className="mt-3">By Agreeing To Our Code Of Conduct, You Also Agree To Adhere To Our <Link to="/terms" className="text-decoration-none">Terms Of Service</Link></p>
        </Card>
      </Container>
    </div>
  );
};

export default CodeOfConduct;